name: draft-store-perf-test-aat
trigger: none
pr: none
variables:
  s2sTesting: false
  agentPool: hmcts-cftptl-agent-pool
  serviceConnection: azurerm-qa
  draftStoreBaseUrl: http://draft-store-service.service.core-compute-perftest.internal/drafts
  draftStoreKeyVaultName: draft-store-perftest
  s2sUrl: http://rpe-service-auth-provider-perftest.service.core-compute-perftest.internal
  idamClientId: ccd_gateway
  idamUrl: https://idam-api.perftest.platform.hmcts.net
  idamRedirectUrl: https://www-ccd.perftest.platform.hmcts.net/oauth2redirect

jobs:
  - template: azure-pipelines.yaml
    parameters:
      s2sTesting: $(s2sTesting)
      agentPool: $(agentPool)
      serviceConnection: $(serviceConnection)
      testUsers: $(testUsers)                        # from UI
      testRampUpSecs: $(testRampUpSecs)              # from UI
      testCleanUpDelaySecs: $(testCleanUpDelaySecs)  # from UI
      draftStoreBaseUrl: $(draftStoreBaseUrl)
      draftStoreKeyVaultName: $(draftStoreKeyVaultName)
      s2sUrl: $(s2sUrl)
      idamClientId: $(idamClientId)
      idamUrl: $(idamUrl)
      idamRedirectUrl: $(idamRedirectUrl)
