name: draft-store-perf-test
trigger: none
pr: none
variables:
  DraftStoreKeyVaultName: 'draft-store-sprod'
  serviceConnection: 'azurerm-sandbox'

jobs:
  - job: DraftStorePerfTests
    pool:
      name: mgmt-aks-sandbox
    workspace:
      clean: all
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get secrets from draft-store keyvault'
        inputs:
          azureSubscription: $(serviceConnection)
          keyVaultName: $(DraftStoreKeyvaultName)
          secretsFilter: 'idam-client-secret-for-tests'
      - task: Bash@3
        displayName: 'Execute Gatling Tests'
        inputs:
          targetType: inline
          failOnStderr: false
          script: |
            ./gradlew --no-daemon gatlingRun-uk.gov.hmcts.reform.draftstore.CreateMultipleDrafts
        env:
          DRAFT_STORE_BASE_URL: https://draft-store-service.service.core-compute-sprod.internal
          S2S_URL: https://rpe-service-auth-provider.service.core-compute-sprod.internal
          IDAM_URL: http://idam-api-idam-sprod.service.core-compute-idam-sprod.internal
          IDAM_CLIENT_SECRET: $(idam-client-secret-for-tests)
          IDAM_REDIRECT_URI: https://cmc-citizen-frontend-sprod-staging.service.core-compute-sprod.internal/receiver
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'gatlingReport'
          targetPath: 'build/reports'
