parameters:
  s2sTesting: ''
  agentPool: ''
  serviceConnection: ''
  testUsers: ''
  testRampUpSecs: ''
  testCleanUpDelaySecs: ''
  draftStoreBaseUrl: ''
  draftStoreKeyVaultName: ''
  s2sUrl: ''
  idamUrl: ''
  idamRedirectUrl: ''

jobs:
  - job: DraftStorePerfTests
    timeoutInMinutes: 0
    pool:
      name: ${{ parameters.agentPool }}
    workspace:
      clean: all
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get secrets from draft-store keyvault'
        inputs:
          azureSubscription: ${{ parameters.serviceConnection }}
          keyVaultName: ${{ parameters.draftStoreKeyvaultName }}
          secretsFilter: 'idam-client-secret-for-tests,s2s-secret-for-tests'
      - task: Bash@3
        displayName: 'Execute Gatling Tests'
        inputs:
          targetType: inline
          failOnStderr: false
          continueOnError: true
          script: |
            ./gradlew --no-daemon gatlingRun-uk.gov.hmcts.reform.draftstore.CreateMultipleDrafts
        env:
          DRAFT_STORE_BASE_URL: ${{ parameters.drafStoreBaseUrl }}
          S2S_URL_FOR_TESTS: ${{ parameters.s2sUrl }}
          USE_S2S_TESTING_SUPPORT: ${{ parameters.s2sTesting }}
          S2S_SECRET_FOR_TESTS: ${{ parameters.s2sUrl }}
          IDAM_URL_FOR_TESTS: ${{ parameters.idamUrl }}
          IDAM_CLIENT_SECRET_FOR_TESTS: $(idam-client-secret-for-tests)
          IDAM_REDIRECT_URI_FOR_TESTS: ${{ parameters.idamRedirectUrl }}
          TEST_USERS:  ${{ parameters.testUsers }}
          TEST_RAMP_UP_SECS: ${{ parameters.testRampUpSecs }}
          TEST_CLEAN_UP_DELAY_SECS: ${{ parameters.testCleanUpDelaySecs }}
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'gatlingReport'
          targetPath: 'build/reports'
