name: draft-store-perf-test
trigger: none
pr: none
variables:
  DraftStoreKeyVaultName: 'draft-store-sprod'
  serviceConnection: 'azurerm-sandbox'
  s2sTesting: false
  testUsers:  5 #1500
  testRampUpSecs: 15 #3600
  testCleanUpDelaySecs: 30 #3300

jobs:
  - job: DraftStorePerfTests
    timeoutInMinutes: 0
    pool:
      name: mgmt-aks-sandbox
    workspace:
      clean: all
    steps:
      - task: AzureKeyVault@1
        displayName: 'Get secrets from draft-store keyvault'
        inputs:
          azureSubscription: $(serviceConnection)
          keyVaultName: $(DraftStoreKeyvaultName)
          secretsFilter: 'idam-client-secret-for-tests,s2s-secret-for-tests'
      - task: Bash@3
        displayName: 'Execute Gatling Tests'
        inputs:
          targetType: inline
          failOnStderr: false
          continueOnError: true
          script: |
            ./gradlew --no-daemon gatlingRun-uk.gov.hmcts.reform.draftstore.CreateMultipleDrafts
        env:
          DRAFT_STORE_BASE_URL: http://draft-store-service-sprod.service.core-compute-sprod.internal/drafts
          S2S_URL_FOR_TESTS: https://rpe-service-auth-provider-sprod.service.core-compute-sprod.internal
          USE_S2S_TESTING_SUPPORT: $(s2sTesting)
          S2S_SECRET_FOR_TESTS: $(s2s-secret-for-tests)
          IDAM_URL_FOR_TESTS: http://idam-api-idam-sprod.service.core-compute-idam-sprod.internal
          IDAM_CLIENT_SECRET_FOR_TESTS: $(idam-client-secret-for-tests)
          IDAM_REDIRECT_URI_FOR_TESTS: https://cmc-citizen-frontend-sprod-staging.service.core-compute-sprod.internal/receiver
          TEST_USERS:  $(testUsers)
          TEST_RAMP_UP_SECS: $(testRampUpSecs)
          TEST_CLEAN_UP_DELAY_SECS: $(testCleanUpDelaySecs)
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: 'gatlingReport'
          targetPath: 'build/reports'
